services:
#  ragbot:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - DATABASE_URL=postgres://postgres:password@db:5432/knowledge
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#      - USE_LOCAL_MODEL=false
#      - USER_TELEGRAM_TOKEN=${USER_TELEGRAM_TOKEN}
#      - ADMIN_TELEGRAM_TOKEN=${ADMIN_TELEGRAM_TOKEN}
#      - ADMIN_CHAT_IDS=${ADMIN_CHAT_IDS}
#    depends_on:
#      - db
  db:
    image: pgvector/pgvector:pg14
    environment:
      POSTGRES_DB: knowledge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    command: postgres -c shared_preload_libraries=pgvector
#volumes:
#  db_data: